version: 2
updates:
  # Frontend dependencies (package.json)
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'fritzprix'
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        dependency-type: 'development'
      production-dependencies:
        dependency-type: 'production'

  # Rust dependencies (Cargo.toml)
  - package-ecosystem: 'cargo'
    directory: '/src-tauri'
    schedule:
      interval: 'weekly'
    assignees:
      - 'fritzprix'
    open-pull-requests-limit: 10

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'fritzprix'
    open-pull-requests-limit: 5
