pub mod channel_routing;
pub mod command_parser;
pub mod compact_recovery;
pub mod compaction_text;
pub mod concurrency;
pub mod config;
pub mod config_resolve;
pub mod context;
pub mod events;
pub mod lifecycle;
pub mod llm;
pub mod message_merge;
pub mod pending_queue;
pub mod references;
pub mod runtime_state;
pub mod session_bus;
pub mod session_manager;
pub mod state;
pub mod tauri_events;
pub mod tool_approvals;
pub mod tools;
pub mod types;
pub mod workflow;

pub use crate::execution_mode::ExecutionMode;
pub use config::AgentConfig;
pub use config_resolve::{
    extract_assistant_id_from_session, resolve_agent_config, stable_prompt_source_key,
};
pub use session_manager::AgentSessionManager;
