name: 📦 Release SynapticFlow
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: 🚀 Setup Environment
        uses: ./.github/actions/setup-tauri-env
        with:
          install-tauri-deps: ${{ matrix.platform == 'ubuntu-latest' && 'true' || 'false' }}
          node-version: 'lts/*'

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'SynapticFlow v__VERSION__'
          releaseBody: |
            🚀 **SynapticFlow v__VERSION__** 

            A High-Freedom AI Agent Platform - Infinitely Expandable with MCP!

            ## 🎯 What's New
            - Enhanced AI agent role management
            - Improved MCP server integration  
            - Better file attachment handling
            - Performance optimizations

            ## 📦 Installation

            ### Windows
            Download and run `SynapticFlow_x64_en-US.msi`

            ### macOS
            Download `SynapticFlow.app.tar.gz`, extract and copy to Applications folder

            ### Linux
            - **Ubuntu/Debian**: Download and install `.deb` package
            - **AppImage**: Download `.AppImage`, make executable and run

            ## 🔧 Requirements
            - Windows 10+ / macOS 10.15+ / Linux (modern distribution)
            - 4GB RAM minimum, 8GB recommended

            See the assets below to download for your platform.
          releaseDraft: true
          prerelease: false
