name: 📦 Release SynapticFlow
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (e.g. v0.1.1). If omitted when manually dispatching, the pushed tag (if any) will be used.'
        required: false
        default: ''

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Sync node version and setup cache
        uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install frontend dependencies
        run: pnpm install

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.event.inputs.tag != '' && github.event.inputs.tag || github.ref_name }}
          releaseName: SynapticFlow ${{ github.event.inputs.tag != '' && github.event.inputs.tag || github.ref_name }}
          releaseBody: |
            A High-Freedom AI Agent Platform - Infinitely Expandable with MCP!

            ## 🎯 What's New
            - Enhanced AI agent role management
            - Improved MCP server integration
            - Better file attachment handling
            - Performance optimizations

            ## 📦 Installation

            ### Windows
            Download and run `SynapticFlow_x64_en-US.msi`

            ### macOS
            Download `SynapticFlow.app.tar.gz`, extract and copy to Applications folder

            ### Linux
            - **Ubuntu/Debian**: Download and install `.deb` package
            - **AppImage**: Download `.AppImage`, make executable and run

            ## 🔧 Requirements
            - Windows 10+ / macOS 10.15+ / Linux (modern distribution)
            - 4GB RAM minimum, 8GB recommended

            See the assets below to download for your platform.
          releaseDraft: false
          prerelease: false
